### ISSUE TITLE
Plugin gradually eats CPU time, leaks memory

### ISSUE THREAD

**Issue by xenimax** [KillerBOSS2019/Windows-Mover#1]
When the plugin executable is run, it slowly -- over the course of a couple of hours -- starts eating more and more CPU time, and its memory footprint grows as it does.  Presumably, this continues until its execution thread manages to peg the CPU core it's squatting on, but I haven't let it run long enough at a stretch to truly achieve maximum chonk.

My Python knowledge is pretty rudimentary, but I poked around the source code to see if I could float a guess at what's happening.  I've got a poorly-informed hunch that the problem might center around the _OptionList_ array in _list_windows_.

Lines 21-33:
```
OptionList = []
def list_windows():
    @WNDENUMPROC
    def enum_proc(hWnd, lParam):
        if user32.IsWindowVisible(hWnd):
            length = user32.GetWindowTextLengthW(hWnd) + 1
            title = ctypes.create_unicode_buffer(length)
            user32.GetWindowTextW(hWnd, title, length)
            if title.value != "":
                OptionList.append(title.value)
        return True
    user32.EnumWindows(enum_proc, 0)
    return list(set(sorted(OptionList)))
```

Note that _OptionList_ is first initialized outside the _list_windows_ function's declaration, and never cleared after that.  Then, every time _list_windows_ is called, more values are appended to _OptionList_, which is then sorted and returned.  This looks about like what I suspected was happening -- _OptionList_ grows over time, and the cost to sort it becomes unwieldy as it does.  I _think_ just moving the _OptionList_ initialization inside _list_windows_ would resolve the issue -- but again, my Python is hot garbage.

Anyway, best regards.

**Comment by DamienStaebler** [comment]
Thanks I didn't noticed until now will take your suggestion and test it

**Comment by KillerBOSS2019** [comment]
May I ask how long have you waited for it to see the difference?

**Comment by xenimax** [comment]
Not sure if you deleted a comment from the issue thread but:

> May I ask how long have you waited for it to see the difference?

I want to say that after somewhere around 3 hours it was pulling a consistant 4% CPU utilization on my Ryzen 3700x (8c/16t), which amounts to about a third of one CPU core.  I've seen it as high as a persistant 6% utilization, or half of a CPU core -- but I have no idea how long that was, and I ended up killing the process without troubleshooting.
