### ISSUE TITLE
restore from systray

### ISSUE THREAD

**Issue by Tomatoschewps** [KillerBOSS2019/Windows-Mover#2]
Hi,

1st, thanks for your work, it's a great plugin for Touch portal !

I've try today to get focus to my VoIP app (Zoiper5).
It's ok if Zoiper is just in background (with 'focus' obviously ^^) but in the case where Zoiper is minimized it won't work even if I use restore or maximize.
Zoiper get to systray when minimized and I've seen that WindowsMover don't list app when they are in systray.

is there any workaround ?

D.

**Comment by DamienStaebler** [comment]
No theres no way around it since it's in systray it doesnt have GUI unlike other ones like minimized app has a GUI

**Comment by Tomatoschewps** [comment]
ok ...
