### ISSUE TITLE
Exception when moving window on slightly non-standard multimonitor config

### ISSUE THREAD

**Issue by xenimax** [KillerBOSS2019/Windows-Mover#4]
Trying to use "Advanced Move Window by presets" to move a window to "Top Right" on "Display-1" results in WinMover's support application throwing an exception.  Moving the window to "Top Right of "Display-0" works.

Two monitors, side by side -- main monitor ("Display-0"; 2560x1440@165hz) on the left; second monitor ("Display-1"; 1280x1024@60hz) on the right.  When they're in the default configuration, with the top of the two displays aligned, it works just fine.  If I offset "Display-1" down 290px in the display control panel to better align them, WinMover's support application throws an exception.

To illustrate...
This monitor configuration works:
```
|-----------------------------------|
|                         |Display-1|
|                         |         |
|        Display-0        |---------|
|                         |
|                         |
|-------------------------|
```

This monitor configuration breaks v2.0.4+:
```
|-------------------------|
|                         |
|                         |---------|
|        Display-0        |Display-1|
|                         |         |
|                         |---------|
|-------------------------|
```

Tested on Touch Portal 2.3.10 and 3.0.8.  Running Windows 10 21H2.

Here's the Debug.bat output:

v2.0.3
```
C:\Users\USERNAME\AppData\Roaming\TouchPortal\plugins\Window-Mover>WinMover.exe
updating
{'tpVersionString': '2.3.010', 'pluginVersion': 203, 'tpVersionCode': 203010, 'sdkVersion': 3, 'type': 'info', 'status': 'paired'}
{'data': [{'id': 'KillerBOSS.TP.Plugins.WindowMover.Windowpresets.Advanced.Presets', 'value': 'Top Right'}, {'id': 'KillerBOSS.TP.Plugins.WindowMover.Advanced.Windowpreset.Window', 'value': 'PROGRAMNAME'}, {'id': 'KillerBOSS.TP.Plugins.WindowMover.Windowpresets.Advanced.Displays', 'value': 'Display-1'}, {'id': 'KillerBOSS.TP.Plugins.WindowMover.Windowpresets.Advanced.AllowResize', 'value': 'False'}], 'pluginId': 'WindowMover', 'actionId': 'KillerBOSS.TP.Plugins.WindowMover.Advanced.Windowpresets', 'type': 'action'}
['Display-0', 'Display-1']
{'Display-1': {'width': 1280, 'height': 1024, 'x': 2560, 'y': 290}}
```

v2.0.4
```
C:\Users\USERNAME\AppData\Roaming\TouchPortal\plugins\Window-Mover>WinMover.exe
updating
{'settings': [{'Build by': 'Killer_BOSS'}, {'Version': '2.0.4'}, {'Is Running': 'True'}], 'tpVersionString': '2.3.010', 'pluginVersion': 204, 'tpVersionCode': 203010, 'sdkVersion': 3, 'type': 'info', 'status': 'paired'}
Exception in thread Thread-57:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 1254, in run
  File "TouchPortalAPI\__init__.py", line 68, in __onReceiveCallback
  File "pyee\_base.py", line 113, in emit
  File "pyee\_base.py", line 96, in _call_handlers
  File "pyee\_base.py", line 81, in _emit_run
  File "main.py", line 303, in ManageAction
  File "main.py", line 59, in Move_Window
pywintypes.error: (1461, 'GetMonitorInfo', 'Invalid monitor handle.')
```

v2.1.0
```
C:\Users\USERNAME\AppData\Roaming\TouchPortal\plugins\Window-Mover>WinMover.exe
updating Display List ['Display-0', 'Display-1']
{'settings': [{'Build by': 'Killer_BOSS'}, {'Version': '2.1'}, {'Is Running': 'True'}], 'tpVersionString': '2.3.010', 'pluginVersion': 2100, 'tpVersionCode': 203010, 'sdkVersion': 3, 'type': 'info', 'status': 'paired'}
Exception in thread Thread-37:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 1254, in run
  File "TouchPortalAPI\__init__.py", line 67, in __onReceiveCallback
  File "pyee\_base.py", line 113, in emit
  File "pyee\_base.py", line 96, in _call_handlers
  File "pyee\_base.py", line 81, in _emit_run
  File "main.py", line 327, in ManageAction
  File "main.py", line 59, in Move_Window
pywintypes.error: (1461, 'GetMonitorInfo', 'Invalid monitor handle.')
```

**Comment by DamienStaebler** [comment]
Same problem with latest build TP 3.0.8?

**Comment by DamienStaebler** [comment]
Seems like this is the line that's causing the problem

https://github.com/KillerBOSS2019/Windows-Mover/blob/main/src/main.py#L59

```py
monitor_area = win32api.GetMonitorInfo(user32.MonitorFromPoint(Monitor[indexnum][Display]['x'],Monitor[indexnum][Display]['y']))
```

**Comment by xenimax** [comment]
> Same problem with latest build TP 3.0.8?

Yes.


> Seems like this is the line that's causing the problem
> 
> https://github.com/KillerBOSS2019/Windows-Mover/blob/main/src/main.py#L59
> 
> ```python
> monitor_area = win32api.GetMonitorInfo(user32.MonitorFromPoint(Monitor[indexnum][Display]['x'],Monitor[indexnum][Display]['y']))
> ```

Eyeballing the documentation, looks like you could be passing the wrong parameters to MonitorFromPoint?

https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-monitorfrompoint

You're passing it (X_Coordinate, Y_Coordinate), but what it actually wants is (tagPOINT_Structure, Behavior_Constant), where tagPOINT_Structure is a structure containing the coordinates, and Behavior_Constant tells MonitorFromPoint what to do if it doesn't like what it sees in tagPOINT_Structure.  So, when the monitor's origin point has a Y axis coordinate of zero, it reads that as "MONITOR_DEFAULTTONEAREST", and so its failure behavior happens to guess its way to the right monitor.


Not sure, but maybe something like this is somewhere around the right direction:
```
point = tagPOINT(Monitor[indexnum][Display]['x'], Monitor[indexnum][Display]['y'])
# https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-monitorfrompoint
monitor_area = win32api.GetMonitorInfo(point, MONITOR_DEFAULTTONEAREST)

```

**Comment by xenimax** [comment]
Hopped in to check the status on this and just realized that I screwed up my code snippet.  Should have been:

```
point = tagPOINT(Monitor[indexnum][Display]['x'], Monitor[indexnum][Display]['y'])
# https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-monitorfrompoint
monitor_area = win32api.GetMonitorInfo(user32.MonitorFromPoint(point, MONITOR_DEFAULTTONEAREST))
```

_(Still don't know that it's the right fix, and my Python build environment is kinda broken, ATM...)_

**Comment by DamienStaebler** [comment]
what is `tagPOINT`? is that a method comes with User32.dll?

**Comment by xenimax** [comment]
Win32 structure for holding the coordinate values of a point, which MonitorFromPoint seems to be looking for.  (https://docs.microsoft.com/en-us/windows/win32/api/windef/ns-windef-point)

Imported from [wintypes](https://github.com/python/cpython/blob/c8a47e76a391c8818bf10a282cdcd3bb5c23ebf6/Lib/ctypes/wintypes.py#L115), so you should already be set to use it (I think?).

**Comment by KillerBOSS2019** [comment]
From my test the `win32api.GetMonitorInfo` won't accept 2 parameter I passed in `win32api.tagPOINT(x, y)` and `MONITOR_DEFAULTTONEAREST`

**Comment by KillerBOSS2019** [comment]
I might need to try to access the API directly maybe? Eg load dll using ctypes

**Comment by DamienStaebler** [comment]
![image](https://user-images.githubusercontent.com/55416314/165002491-6dd86ad0-e817-4965-9948-61cd14f1c3e1.png)
so far from my test no luck

**Comment by xenimax** [comment]
```
C:\>py
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>>
>>> import win32api
>>> import ctypes
>>> from ctypes import wintypes
>>> from ctypes.wintypes import tagPOINT
>>>
>>> user32 = ctypes.WinDLL('user32')
>>>
>>> MONITOR_DEFAULTTONULL = 0
>>> MONITOR_DEFAULTTOPRIMARY = 1
>>> MONITOR_DEFAULTTONEAREST = 2
>>>
>>>
>>> win32api.GetMonitorInfo(user32.MonitorFromPoint(tagPOINT(3700,0),MONITOR_DEFAULTTONEAREST))
{'Monitor': (2560, 290, 3840, 1314), 'Work': (2560, 290, 3840, 1274), 'Flags': 0, 'Device': '\\\\.\\DISPLAY10'}
>>>
>>> win32api.GetMonitorInfo(user32.MonitorFromPoint(tagPOINT(3700,0),MONITOR_DEFAULTTOPRIMARY))
{'Monitor': (0, 0, 2560, 1440), 'Work': (0, 0, 2496, 1440), 'Flags': 1, 'Device': '\\\\.\\DISPLAY9'}
>>>
>>> win32api.GetMonitorInfo(user32.MonitorFromPoint(tagPOINT(3700,0),MONITOR_DEFAULTTONULL))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pywintypes.error: (1461, 'GetMonitorInfo', 'Invalid monitor handle.')
>>>
>>>
>>>
>>> user32.MonitorFromPoint(tagPOINT(3700,0),MONITOR_DEFAULTTONEAREST)
-4715143
>>>
>>> user32.MonitorFromPoint(tagPOINT(3700,0),MONITOR_DEFAULTTOPRIMARY)
1285163677
>>>
>>> user32.MonitorFromPoint(tagPOINT(3700,0),MONITOR_DEFAULTTONULL)
0
>>>
>>>
>>> quit()

C:\>
```


That said, it might be (slightly) simpler to use to use "win32api.MonitorFromPoint":


```
C:\>py
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>>
>>> import win32api
>>>
>>> MONITOR_DEFAULTTONULL = 0
>>> MONITOR_DEFAULTTOPRIMARY = 1
>>> MONITOR_DEFAULTTONEAREST = 2
>>>
>>>
>>> win32api.GetMonitorInfo(win32api.MonitorFromPoint((3700,0),MONITOR_DEFAULTTONEAREST))
{'Monitor': (2560, 290, 3840, 1314), 'Work': (2560, 290, 3840, 1274), 'Flags': 0, 'Device': '\\\\.\\DISPLAY10'}
>>>
>>> win32api.GetMonitorInfo(win32api.MonitorFromPoint((3700,0),MONITOR_DEFAULTTOPRIMARY))
{'Monitor': (0, 0, 2560, 1440), 'Work': (0, 0, 2496, 1440), 'Flags': 1, 'Device': '\\\\.\\DISPLAY9'}
>>>
>>> win32api.GetMonitorInfo(win32api.MonitorFromPoint((3700,0),MONITOR_DEFAULTTONULL))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pywintypes.error: (1461, 'GetMonitorInfo', 'Invalid monitor handle.')
>>>
>>>
>>>
>>> win32api.MonitorFromPoint((3700,0),MONITOR_DEFAULTTONEAREST)
<PyHANDLE:-4715143>
>>>
>>> win32api.MonitorFromPoint((3700,0),MONITOR_DEFAULTTOPRIMARY)
<PyHANDLE:1285163677>
>>>
>>> win32api.MonitorFromPoint((3700,0),MONITOR_DEFAULTTONULL)
>>>
>>>
>>> quit()

C:\>
```


First argument for win32api.MonitorFromPoint is a tuple "(X_Coord, Y_Coord)".  Second argument is the (poorly documented) behavior flag, where 0=MONITOR_DEFAULTTONULL, 1=MONITOR_DEFAULTTOPRIMARY, and 2=MONITOR_DEFAULTTONEAREST.

**Comment by DamienStaebler** [comment]
I've made a PR which you can test out (Let me know if you want me to compile it for you)

**Comment by xenimax** [comment]
Took a minute for me to realize it was built against a version of TouchPortal-API that hadn't been released yet...

In any case, it looks like it fixes the monitor issue,

**Comment by DamienStaebler** [comment]
ill compile it then. forgot that I used a version that I haven't officially released yet xD
